stages:
    - build
    - test
    

build:
    stage: build
    only:
    - dev
    script: "mvn clean package -DskipTests"


test:
    stage: test
    only:
    - dev
    script:
        - echo "Test"

