create table person
(
    id                  int4 generated by default as identity,
    about               varchar(2048) not null,
    birth_date          date          not null,
    confirmation_code   varchar(45)   not null,
    e_mail              varchar(255)  not null,
    first_name          varchar(255)  not null,
    is_approved         bit(1)        not null,
    is_blocked          bit(1)        not null,
    last_name           varchar(255)  not null,
    last_online_time    timestamp     not null,
    messages_permission varchar(255)  not null,
    password            varchar(255)  not null,
    phone               int4,
    photo               varchar(2048) not null,
    reg_date            date          not null,
    town                varchar(45)   not null,
    primary key (id)
);